/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttms.frontend;

/**
 *
 * @author Esha
 */
public class TrainTTRow extends javax.swing.JPanel {

    /**
     * Creates new form TrainTT
     */
    public TrainTTRow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        train_name = new javax.swing.JLabel();
        source_station = new javax.swing.JLabel();
        destination_station = new javax.swing.JLabel();
        arrival_time = new javax.swing.JLabel();
        departure_time = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        train_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        train_name.setForeground(new java.awt.Color(27, 120, 138));
        train_name.setText("TrainName");

        source_station.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        source_station.setForeground(new java.awt.Color(27, 120, 138));
        source_station.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        source_station.setText("SourceStation");

        destination_station.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        destination_station.setForeground(new java.awt.Color(27, 120, 138));
        destination_station.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        destination_station.setText("DestinationStation");

        arrival_time.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        arrival_time.setForeground(new java.awt.Color(27, 120, 138));
        arrival_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrival_time.setText("ArrivalTime");

        departure_time.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        departure_time.setForeground(new java.awt.Color(27, 120, 138));
        departure_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departure_time.setText("DepartureTime");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(source_station)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destination_station)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrival_time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departure_time)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(train_name)
                    .addComponent(source_station)
                    .addComponent(destination_station)
                    .addComponent(arrival_time)
                    .addComponent(departure_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTrainName(String name){
        this.train_name.setText(name);
    }
    public void setSourceStation(String name){
        this.source_station.setText(name);
    }
    public void setDestinationStation(String name){
        this.destination_station.setText(name);
    }
    public void setArrivalTime(String name){
        this.arrival_time.setText(name);
    }
    public void setDepartureTime(String name){
        this.departure_time.setText(name);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrival_time;
    private javax.swing.JLabel departure_time;
    private javax.swing.JLabel destination_station;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel source_station;
    private javax.swing.JLabel train_name;
    // End of variables declaration//GEN-END:variables
}
